[package]
name = "scoped_static"
description = "Safe promotion of lifetimes to static"
license = "Apache-2.0"
version = "0.0.1"
edition = "2024"

[dependencies]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["min_safety"]
# If disabled, there is no runtime safety checks in non-debug mode.
# Increasing the risk of UB. But a lot more efficient since no underlying `Arc` is used.
# Only consider disabling this if one is certain `Scoped` is dropped after all `Lifted`.
min_safety = []