[package]
name = "scope"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["min_safety"]
# If disabled, there is no runtime safety checks in non-debug mode.
# Increasing the risk of UB. But a lot more efficient since no underlying `Arc` is used.
# Only consider disabling this if one is certain `Scope` is dropped after all `SArc`.
min_safety = []