[package]
name = "scoped_static"
description = "Safe promotion of lifetimes to static"
license = "Apache-2.0"
version = "0.0.1"
edition = "2024"

[dependencies]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = []
# Enabling will force checks for the unchecked types. Making them perform exactly like
# the checked versions.
checked = []