name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests release
      run: cargo test --release --verbose

    - name: Set up Rust (nightly) for Miri
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install Miri
      run: rustup component add miri
    - name: Run known safe tests with Miri
      run: "MIRIFLAGS=-Zmiri-ignore-leaks cargo miri test --lib tests::normal_test::"
    - name: Run tests that are known to fail with Miri
      run: |
        set -euo pipefail
        # List only UB test functions (not modules)
        TESTS=$(cargo test tests::ub_tests:: -- --list --format terse | grep 'tests::ub_tests::' | cut -d: -f1)
        echo "UB tests found:"
        echo "$TESTS"
        echo

        EXITCODE=0
        for t in $TESTS; do
          echo "Running UB test: $t"
          if MIRIFLAGS="-Zmiri-ignore-leaks" cargo miri test --lib "$t" -- --exact; then
            echo "❌ ERROR: UB test '$t' unexpectedly PASSED"
            EXITCODE=1
          else
            echo "✅ UB test '$t' failed as expected (Miri detected UB)"
          fi
          echo
        done

        exit $EXITCODE